spring.application.name=new_rms

logging.level.org.springframework.security=TRACE

server.error.whitelabel.enabled=false

spring.thymeleaf.cache=false

#server.port=8081

db.host=localhost
db.port=1521
db.service.name=FREEPDB1
db.username=SYSTEM
db.password=123456

# Oracle database
spring.datasource.url=jdbc:oracle:thin:@${db.host}:${db.port}/${db.service.name}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# jpa - sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
## tao bang truoc khi insert data
spring.jpa.defer-datasource-initialization=true
## chay file data.sql
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/mock-data/role.sql, classpath:/mock-data/recruitment_process.sql, classpath:/mock-data/admin.sql, \
  classpath:/mock-data/recruiter.sql, classpath:/mock-data/skill.sql, \
  classpath:/mock-data/stage.sql, classpath:/mock-data/candidate.sql


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rms.jobbridge@gmail.com
spring.mail.password=prkrtgwpuefdpogq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=698554025421-o1bcv6aoclhmbdeq14to6dbn5r4q68qm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/api/oauth2/login/google
spring.security.oauth2.client.registration.google.scope=email,profile


# Rms application
rms.otp.duration=300
rms.otp.max.attempt=5
rms.otp.window=3600
rms.otp.interval=60
rms.oauth2.code.duration=30

rms.jwt.access.token.key=thisIsASecretKeyWithAtLeast32CharactersLongForAccessToken!
rms.jwt.access.token.expiration=86400
rms.jwt.refresh.token.key=thisIsASecretKeyWithAtLeast32CharactersLongForRefreshToken!
rms.jwt.refresh.token.expiration=604800

spring.jackson.date-format=dd/MM/yyyy

rms.frontend.url=http://localhost:3000