spring.application.name=rms

logging.level.org.springframework.security=TRACE

db.host=localhost
db.port=1521
db.sid=free
db.username=c##dat
db.password=1

#Oracle database
spring.datasource.url=jdbc:oracle:thin:@${db.host}:${db.port}:${db.sid}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver




spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


#spring.sql.init.platform=oracle

# Chay file data.sql
spring.sql.init.mode=always

# Hibernate tao bang truoc khi insert data tu data.sql
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.tryItOutEnabled=true

server.error.whitelabel.enabled=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rms.jobbridge@gmail.com
spring.mail.password=prkrtgwpuefdpogq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



