spring.application.name=rms

logging.level.org.springframework.security=TRACE

db.host=localhost
db.port=1521
db.sid=free
db.username=c##dat
db.password=1

#Oracle database
spring.datasource.url=jdbc:oracle:thin:@${db.host}:${db.port}:${db.sid}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Chay file data.sql
spring.sql.init.mode=always

spring.sql.init.data-locations=classpath:/mock-data/role.sql, classpath:/mock-data/skill.sql, classpath:/mock-data/recruiter.sql,\
  classpath:/mock-data/candidate.sql, classpath:/mock-data/job.sql, classpath:/mock-data/application.sql, classpath:/mock-data/stage.sql

# Hibernate tao bang truoc khi insert data tu data.sql
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.tryItOutEnabled=true
springdoc.override-with-generic-response=false

# Tat /error
server.error.whitelabel.enabled=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rms.jobbridge@gmail.com
spring.mail.password=prkrtgwpuefdpogq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=698554025421-o1bcv6aoclhmbdeq14to6dbn5r4q68qm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/api/auth/google/login
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.facebook.client-id=544432291719072
spring.security.oauth2.client.registration.facebook.client-secret=ddc25906cbf1ee6893f2327a15e7416c
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/api/auth/facebook/login
spring.security.oauth2.client.registration.facebook.scope=email




otp-expiration-time-in-second=300
duration-between-otp-request-in-second=60
duration-between-otp-interval-in-second=3600
the-maximum-number-of-otp-requests-between-interval=5