ALTER TABLE admins MODIFY (admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO ADMINS (admin_id, username, role_id, password)
values (1, 'admin', 3, '$2a$10$0pwfpJGuCoA3NNZ6oY/0y..MhF61xoPlFXf7fQTPqMSJFzjXhgGTe');

ALTER TABLE admins MODIFY (admin_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));