ALTER TABLE candidates_auth MODIFY(auth_id NUMBER GENERATED BY DEFAULT AS IDENTITY);

INSERT INTO candidates_auth (email, password, status, role_id)
VALUES ('candidate1@example.com', -- email
        '$2a$10$z7U3lhyPozc7mKqqfqITSO4JhK8BVh.GkhrLBD60WLoQ3rRYsEqW.',
        'ACTIVE',
        1
       );
INSERT INTO candidates (candidate_id) values (1);

INSERT INTO candidates_auth (email, password, status, role_id)
VALUES ('candidate2@example.com',
        '$2a$10$z7U3lhyPozc7mKqqfqITSO4JhK8BVh.GkhrLBD60WLoQ3rRYsEqW.',
        'ACTIVE',
        1);
INSERT INTO candidates (candidate_id) VALUES (2);

INSERT INTO candidates_auth (email, password, status, role_id)
VALUES ('candidate3@example.com',
        '$2a$10$z7U3lhyPozc7mKqqfqITSO4JhK8BVh.GkhrLBD60WLoQ3rRYsEqW.',
        'ACTIVE',
        1);
INSERT INTO candidates (candidate_id) VALUES (3);

ALTER TABLE candidates_auth MODIFY (auth_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));