ALTER TABLE users MODIFY (user_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

-- Candidate 5 (Based on your example)
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 5, 2, TIMESTAMP '2025-04-04 23:59:59', TIMESTAMP '2025-04-04 23:59:59', 'candidate5@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 5, TO_TIMESTAMP('1990-05-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '123 Fashion Street, Fashion City, 12345', '/example/cv/url', 'MALE', 'John Doe', '123-456-7890', null, 'A passionate fashion designer with over 5 years of experience in concept development and pattern making.');

-- Candidate 6
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 6, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate6@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 6, TO_TIMESTAMP('1992-08-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), '456 Textile Avenue, Fabric Town, 67890', '/example/cv/url', 'FEMALE', 'Jane Smith', '234-567-8901', null, 'Textile specialist with deep knowledge of fabric properties, sourcing, and quality control.');

-- Candidate 7
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 7, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate7@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 7, TO_TIMESTAMP('1988-11-05 14:15:00', 'YYYY-MM-DD HH24:MI:SS'), '789 Trend Road, Style City, 11223', '/example/cv/url', 'MALE', 'Alex Johnson', '345-678-9012', null, 'Experienced Fashion Trend Analyst with a keen eye for emerging styles and market shifts.');

-- Candidate 8
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 8, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate8@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 8, TO_TIMESTAMP('1995-02-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), '101 Pattern Lane, Design District, 44556', '/example/cv/url', 'FEMALE', 'Emily White', '456-789-0123', null, 'Proficient Pattern Maker skilled in both manual drafting and digital pattern creation (CAD).');

-- Candidate 9
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 9, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate9@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 9, TO_TIMESTAMP('1993-07-25 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), '202 Sewing Circle, Craftsville, 77889', '/example/cv/url', 'MALE', 'Michael Brown', '567-890-1234', null, 'Highly skilled Sewer with expertise in garment construction and finishing techniques.');

-- Candidate 10
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 10, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate10@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 10, TO_TIMESTAMP('1991-12-30 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), '303 Design Plaza, Art City, 99001', '/example/cv/url', 'FEMALE', 'Sarah Davis', '678-901-2345', null, 'Creative Fashion Designer specializing in womenswear, strong in sketching and trend integration.');

-- Candidate 11
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 11, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate11@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 11, TO_TIMESTAMP('1989-03-12 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), '404 Fabric Way, Material Town, 22334', '/example/cv/url', 'MALE', 'David Miller', '789-012-3456', null, 'Textile expert with extensive knowledge of sustainable materials and fabric testing.');

-- Candidate 12
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 12, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate12@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 12, TO_TIMESTAMP('1996-06-18 10:10:00', 'YYYY-MM-DD HH24:MI:SS'), '505 Trendsetter St, Vogue Ville, 55667', '/example/cv/url', 'FEMALE', 'Laura Wilson', '890-123-4567', null, 'Fashion Analyst skilled in market research, competitor analysis, and trend reporting.');

-- Candidate 13
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 13, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate13@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 13, TO_TIMESTAMP('1994-09-22 15:20:00', 'YYYY-MM-DD HH24:MI:SS'), '606 Pattern Place, Draftsburg, 88990', '/example/cv/url', 'MALE', 'Robert Moore', '901-234-5678', null, 'Technical Pattern Maker adept at creating accurate patterns for complex garments.');

-- Candidate 14
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 14, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate14@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 14, TO_TIMESTAMP('1990-10-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), '707 Stitch Blvd, Sewing Central, 11002', '/example/cv/url', 'FEMALE', 'Linda Taylor', '012-345-6789', null, 'Master Sewer with experience in haute couture construction and delicate fabrics.');

-- Candidate 15
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 15, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate15@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 15, TO_TIMESTAMP('1997-01-05 17:05:00', 'YYYY-MM-DD HH24:MI:SS'), '808 Designer Drive, Creation County, 33445', '/example/cv/url', 'MALE', 'James Anderson', '112-233-4455', null, 'Innovative Fashion Designer focused on sustainable practices and textile research.');

-- Candidate 16
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 16, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate16@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 16, TO_TIMESTAMP('1992-04-14 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), '909 Textile Terrace, Weaver Ward, 66778', '/example/cv/url', 'FEMALE', 'Patricia Thomas', '223-344-5566', null, 'Textile Technologist experienced in fabric development and performance analysis.');

-- Candidate 17
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 17, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate17@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 17, TO_TIMESTAMP('1987-07-07 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), '111 Trend Ave, Forecast Falls, 99887', '/example/cv/url', 'MALE', 'Christopher Jackson', '334-455-6677', null, 'Senior Fashion Trend Forecaster with international market experience.');

-- Candidate 18
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 18, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate18@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 18, TO_TIMESTAMP('1998-10-28 14:55:00', 'YYYY-MM-DD HH24:MI:SS'), '222 Pattern Path, Blueprint Bay, 22110', null, 'FEMALE', 'Mary Garcia', '445-566-7788', null, 'Detail-oriented Pattern Maker specializing in menswear and tailoring.');

-- Candidate 19
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 19, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate19@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 19, TO_TIMESTAMP('1991-05-01 16:15:00', 'YYYY-MM-DD HH24:MI:SS'), '333 Sewing Street, Stitchburg, 55443', null, 'MALE', 'Daniel Martinez', '556-677-8899', null, 'Industrial Sewer proficient with various machines and production sewing processes.');

-- Candidate 20
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 20, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate20@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 20, TO_TIMESTAMP('1993-11-11 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), '444 Design Drive, Concept Corner, 88776', null, 'FEMALE', 'Jessica Rodriguez', '667-788-9900', null, 'Fashion Designer with a strong background in knitwear design and textile selection.');

-- Candidate 21
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 21, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate21@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 21, TO_TIMESTAMP('1995-09-09 10:40:00', 'YYYY-MM-DD HH24:MI:SS'), '555 Fabric Fairway, Textile Town, 11221', null, 'MALE', 'Paul Lee', '778-899-0011', null, 'Knowledgeable in textile sourcing, import/export regulations, and supply chain management.');

-- Candidate 22
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 22, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate22@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 22, TO_TIMESTAMP('1990-02-25 13:25:00', 'YYYY-MM-DD HH24:MI:SS'), '666 Trend Trail, Style Spot, 44554', null, 'FEMALE', 'Nancy Hernandez', '889-900-1122', null, 'Fashion Trend Analyst adept at translating runway trends into commercial product lines.');

-- Candidate 23
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 23, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate23@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 23, TO_TIMESTAMP('1994-06-30 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), '777 Pattern Parkway, Model Metropolis, 77887', null, 'MALE', 'Mark Lopez', '990-011-2233', null, 'Digital Pattern Maker with expertise in grading and marker making for production efficiency.');

-- Candidate 24
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 24, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate24@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 24, TO_TIMESTAMP('1986-12-12 18:20:00', 'YYYY-MM-DD HH24:MI:SS'), '888 Stitch Studio, Couture City, 33003', null, 'FEMALE', 'Karen Gonzalez', '001-122-3344', null, 'Sample Sewer specializing in creating first prototypes and salesman samples accurately.');

-- Candidate 25
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 25, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate25@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 25, TO_TIMESTAMP('1999-04-03 09:55:00', 'YYYY-MM-DD HH24:MI:SS'), '999 Design Den, Innovation Isle, 66776', null, 'MALE', 'Steven Wilson', '112-233-4456', null, 'Junior Fashion Designer eager to contribute creative ideas and learn pattern making.');

-- Candidate 26
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 26, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate26@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 26, TO_TIMESTAMP('1991-08-17 11:10:00', 'YYYY-MM-DD HH24:MI:SS'), '121 Fabric Center, Material Metro, 99889', null, 'FEMALE', 'Susan Anderson', '223-344-5567', null, 'Textile Librarian with strong organizational skills and knowledge of fabric swatches and sourcing.');

-- Candidate 27
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 27, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate27@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 27, TO_TIMESTAMP('1994-11-29 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), '232 Trend Track, Insight Inlet, 11001', null, 'MALE', 'Kevin Thomas', '334-455-6678', null, 'Assistant Trend Analyst supporting research and presentation development.');

-- Candidate 28
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 28, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate28@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 28, TO_TIMESTAMP('1997-05-19 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), '343 Pattern Place, Draft Depo, 44332', null, 'FEMALE', 'Ashley Jackson', '445-566-7789', null, 'Pattern Making Assistant experienced in digitizing patterns and creating spec sheets.');

-- Candidate 29
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 29, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate29@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 29, TO_TIMESTAMP('1992-10-01 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), '454 Sewing Suite, Garment Grove, 77665', null, 'MALE', 'Brian White', '556-677-8890', null, 'Skilled Sewer specializing in alterations and custom fittings.');

-- Candidate 30
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 30, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate30@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 30, TO_TIMESTAMP('1996-03-23 12:45:00', 'YYYY-MM-DD HH24:MI:SS'), '565 Design District, Creative Corner, 99009', null, 'FEMALE', 'Amanda Harris', '667-788-9901', null, 'Fashion Designer experienced in technical sketching and creating tech packs for production.');

-- Candidate 31
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 31, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate31@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 31, TO_TIMESTAMP('1988-07-14 08:15:00', 'YYYY-MM-DD HH24:MI:SS'), '676 Textile Trail, Weave World, 22112', null, 'MALE', 'Jason Martin', '778-899-0012', null, 'Textile Buyer with experience negotiating prices and managing vendor relationships.');

-- Candidate 32
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 32, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate32@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 32, TO_TIMESTAMP('1995-01-26 13:30:00', 'YYYY-MM-DD HH24:MI:SS'), '787 Trend Terrace, Style Sphere, 55445', null, 'FEMALE', 'Michelle Thompson', '889-900-1123', null, 'Fashion Trend Researcher focusing on color analysis and material trends.');

-- Candidate 33
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 33, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate33@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 33, TO_TIMESTAMP('1993-09-08 15:40:00', 'YYYY-MM-DD HH24:MI:SS'), '898 Pattern Point, Draft Dimension, 88778', null, 'MALE', 'Eric Garcia', '990-011-2234', null, 'Pattern Maker specializing in outerwear and technical garments.');

-- Candidate 34
INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 34, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'candidate34@example.com', '$2a$10$NrwG73Qq.pITKoeYffbPn.pYQtVfPvIh.FLDi0qPdOsfxibV.XkuG', NULL, 'ACTIVE');

INSERT INTO candidates (candidate_id, date_of_birth, address, cv_url, gender, name, phone, profile_picture_url, summary)
VALUES ( 34, TO_TIMESTAMP('1998-02-15 17:50:00', 'YYYY-MM-DD HH24:MI:SS'), '909 Stitch Street, Sew Savvy, 11223', null, 'FEMALE', 'Cynthia Martinez', '001-122-3345', null, 'Production Sewer with high speed and accuracy on multiple machine types.');

ALTER TABLE users MODIFY (user_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 100));