-- Xóa các sequence cũ và tạo lại để đặt lại giá trị
DROP SEQUENCE INDUSTRIES_SEQ;

-- Tạo sequence mới với giá trị bắt đầu mong muốn
CREATE SEQUENCE INDUSTRIES_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE industries MODIFY (industry_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO industries (name) VALUES ('Information Technology');
INSERT INTO industries (name) VALUES ('Fashion');

-- Dòng này không hợp lệ và đã được loại bỏ:
-- ALTER TABLE industries MODIFY (industry_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));
