ALTER TABLE industries MODIFY (industry_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO industries (name) VALUES ('Information Technology');
INSERT INTO industries (name) VALUES ('Fashion');


ALTER TABLE industries MODIFY (industry_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));