ALTER TABLE jobs MODIFY (job_id NUMBER GENERATED BY DEFAULT AS IDENTITY);

INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           1,
           TIMESTAMP '2025-4-4 23:59:59', TIMESTAMP '2025-4-30 23:59:59',
           1, TIMESTAMP '2025-4-4 23:59:59',
           'Health insurance, Work laptop, Company trips',
           'A fashion company is looking for a candidate with deep knowledge in fashion design, fashion trends, and textile knowledge',
           'Knowledge of fashion design and trends, experience in textile technologies',
           '25,000,000 - 35,000,000 VND',
           'OPEN',
           'Fashion Designer with Textile Knowledge and Trend Analysis'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (1, 1, 1); -- Fashion Design
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (1, 2, 0); -- Textile Knowledge
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (1, 3, 1); -- Fashion Trend Analysis

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           2,
           TIMESTAMP '2025-04-05 10:00:00', TIMESTAMP '2025-05-01 23:59:59',
           1, TIMESTAMP '2025-04-05 10:00:00',
           'Flexible hours, Staff discount, Paid workshops',
           'We are hiring a creative designer with strong pattern making and sewing skills for custom fashion collections.',
           'Proficient in pattern making, sewing techniques, and garment construction.',
           '20,000,000 - 30,000,000 VND',
           'OPEN',
           'Custom Garment Pattern Maker & Sewing Specialist'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (2, 4, 1); -- Pattern Making
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (2, 5, 1); -- Sewing

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           3,
           TIMESTAMP '2025-04-06 09:30:00', TIMESTAMP '2025-05-10 18:00:00',
           1, TIMESTAMP '2025-04-06 09:30:00',
           'Annual bonus, International fashion expos, Team lunches',
           'Seeking an expert in fashion trend forecasting with a passion for sustainable design.',
           'Experience in fashion forecasting, sustainability knowledge, research skills.',
           '30,000,000 - 40,000,000 VND',
           'OPEN',
           'Fashion Trend Analyst & Sustainable Designer'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (3, 3, 1); -- Fashion Trend Analysis
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (3, 1, 0); -- Fashion Design

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           4,
           TIMESTAMP '2025-04-06 09:30:00', TIMESTAMP '2025-05-10 18:00:00',
           2, TIMESTAMP '2025-04-06 09:30:00',
           'Health insurance, Remote work options, Professional development opportunities',
           'Looking for a skilled software developer with expertise in AI and machine learning.',
           'Proficiency in programming languages like Python, experience with AI frameworks, and problem-solving skills.',
           '40,000,000 - 50,000,000 VND',
           'OPEN',
           'AI Developer & Machine Learning Expert'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (4, 11, 1);
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (4, 12, 1);

-----------------------------------------------------------------------------------------------------------------------
INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           5,
           TIMESTAMP '2025-04-06 09:30:00', TIMESTAMP '2025-05-10 18:00:00',
           2, TIMESTAMP '2025-04-06 09:30:00',
           'Health insurance, Flexible working hours, Performance bonuses',
           'We are looking for a talented web developer with strong skills in front-end and back-end technologies.',
           'Proficiency in HTML, CSS, JavaScript, React, Spring, and experience with RESTful APIs and database management.',
           '30,000,000 - 40,000,000 VND',
           'OPEN',
           'Full Stack Web Developer'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (5, 6, 1);
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (5, 7, 1);

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO jobs (job_id, created_at, deadline, recruiter_id, updated_at, benefit, description, requirement, salary, status, title)
VALUES (
           6,
           TIMESTAMP '2025-04-06 09:30:00', TIMESTAMP '2025-05-10 18:00:00',
           2, TIMESTAMP '2025-04-06 09:30:00',
           'Health insurance, Performance bonuses, Learning and development opportunities',
           'We are seeking a skilled database administrator to manage and optimize our database systems.',
           'Experience with SQL, database design, optimization, and cloud database technologies. Familiarity with data backup and recovery.',
           '35,000,000 - 45,000,000 VND',
           'OPEN',
           'Database Administrator (DBA)'
       );
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (6, 13, 1);
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (6, 14, 1);
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (6, 15, 1);
INSERT INTO skill_of_job (job_id, skill_id, required) VALUES (6, 16, 1);

-----------------------------------------------------------------------------------------------------------------------

ALTER TABLE jobs MODIFY (job_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));