ALTER TABLE recruiters_auth MODIFY(recruiter_auth_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO recruiters_auth (recruiter_auth_id, username, password, status, role_id)
VALUES (1, 'recruiter1', '$2a$10$XbPrPeBkYgr4FBiHaNnfJOwG7c8crJULLbcthFDIiDTkm/w7YnQa2', 'ACTIVE', '2');
INSERT INTO recruiters (recruiter_id) VALUES (1);


INSERT INTO recruiters_auth (recruiter_auth_id, username, password, status, role_id)
VALUES (2, 'recruiter2', '$2a$10$XbPrPeBkYgr4FBiHaNnfJOwG7c8crJULLbcthFDIiDTkm/w7YnQa2', 'ACTIVE', '2');
INSERT INTO recruiters (recruiter_id) VALUES (2);

ALTER TABLE recruiters_auth MODIFY (recruiter_auth_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));