-- Xóa các sequence cũ và tạo lại để đặt lại giá trị
DROP SEQUENCE RECRUITMENT_PROCESSES_SEQ;

-- Tạo sequence mới với giá trị bắt đầu mong muốn
CREATE SEQUENCE RECRUITMENT_PROCESSES_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE recruitment_processes MODIFY (recruitment_process_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (1, 'Quy trình tuyển Dev Backend');
INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (2, 'Quy trình tuyển Dev Frontend');
INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (3, 'Quy trình tuyển QA');

-- Dòng này không hợp lệ và đã được loại bỏ:
-- ALTER TABLE recruitment_processes MODIFY (recruitment_process_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 10));
