ALTER TABLE recruitment_processes MODIFY (recruitment_process_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (1, 'Quy trình tuyển Dev Backend');
INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (2, 'Quy trình tuyển Dev Frontend');
INSERT INTO recruitment_processes (recruitment_process_id, name) VALUES (3, 'Quy trình tuyển QA');


ALTER TABLE recruitment_processes MODIFY (recruitment_process_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 10));