ALTER TABLE users MODIFY (user_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES ( 1,1, TIMESTAMP '2025-04-04 23:59:59', TIMESTAMP '2025-04-04 23:59:59',
        'recruiter1@example.com',
        '$2a$10$0EpF.0nKjs9mLPiTkDJVJOKGh9FUBRV5QvFz1bMW/HCHdWnXAQRhS',
        NULL, 'ACTIVE'
       );

INSERT INTO recruiters (user_id, description, name, profile_picture_url)
VALUES (1, 'Recruiter in the Fashion Department', 'John Doe', NULL);

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES (2, 1, TIMESTAMP '2025-04-04 23:59:59', TIMESTAMP '2025-04-04 23:59:59',
        'recruiter2@example.com',
        '$2a$10$0EpF.0nKjs9mLPiTkDJVJOKGh9FUBRV5QvFz1bMW/HCHdWnXAQRhS',
        NULL, 'ACTIVE'
       );


INSERT INTO recruiters (user_id, description, name, profile_picture_url)
VALUES (2, 'Recruiter in the IT Department', 'Mary Johnson', NULL);

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES (3, 1, TIMESTAMP '2025-04-04 23:59:59', TIMESTAMP '2025-04-04 23:59:59',
        'recruiter3@example.com',
        '$2a$10$0EpF.0nKjs9mLPiTkDJVJOKGh9FUBRV5QvFz1bMW/HCHdWnXAQRhS',
        NULL, 'ACTIVE'
       );


INSERT INTO recruiters (user_id, description, name, profile_picture_url)
VALUES (3, 'Recruiter in the Finance Department', 'James Smith', NULL);

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO users (user_id, role_id, created_at, updated_at, email, password, refresh_token, status)
VALUES (4, 1, TIMESTAMP '2025-04-04 23:59:59', TIMESTAMP '2025-04-04 23:59:59',
        'recruiter4@example.com',
        '$2a$10$0EpF.0nKjs9mLPiTkDJVJOKGh9FUBRV5QvFz1bMW/HCHdWnXAQRhS',
        NULL, 'ACTIVE'
       );


INSERT INTO recruiters (user_id, description, name, profile_picture_url)
VALUES (4, 'Recruiter in the Marketing Department', 'Emily Chen', NULL);



ALTER TABLE users MODIFY (user_id NUMBER GENERATED ALWAYS AS IDENTITY );