ALTER TABLE recruiters_auth MODIFY(recruiter_auth_id NUMBER GENERATED BY DEFAULT AS IDENTITY);

-- Xóa tài khoản Recruiter 'hacnguyet108@gmail.com' cũ nếu có để script có thể chạy lại
DELETE FROM RECRUITERS WHERE recruiter_id IN (SELECT recruiter_auth_id FROM RECRUITERS_AUTH WHERE username = 'hacnguyet108@gmail.com');
DELETE FROM RECRUITERS_AUTH WHERE username = 'hacnguyet108@gmail.com';

-- Thêm tài khoản Recruiter: hacnguyet108@gmail.com / 123123
-- THAY THẾ HASH MẬT KHẨU BÊN DƯỚI BẰNG HASH THỰC TẾ CỦA "123123"
INSERT INTO recruiters_auth (recruiter_auth_id, username, password, status, role_id)
VALUES (3, 'hacnguyet108@gmail.com', '$2a$10$Y8.xHc7lI45gC/nS0xS.5u0uKjdO.qdft3YQrn7J5g5aKjVH00yB.', 'ACTIVE', 2);
INSERT INTO recruiters (recruiter_id, name, description)
VALUES (3, 'Hac Nguyet Recruiter', 'Tài khoản cho hacnguyet108');

-- Các tài khoản Recruiter hiện có khác
INSERT INTO recruiters_auth (recruiter_auth_id, username, password, status, role_id)
VALUES (1, 'recruiter1', '$2a$10$XbPrPeBkYgr4FBiHaNnfJOwG7c8crJULLbcthFDIiDTkm/w7YnQa2', 'ACTIVE', 2); -- role_id là số
INSERT INTO recruiters (recruiter_id, name, description)
VALUES (1, 'Recruiter One', 'Mô tả cho Recruiter One');


INSERT INTO recruiters_auth (recruiter_auth_id, username, password, status, role_id)
VALUES (2, 'recruiter2', '$2a$10$XbPrPeBkYgr4FBiHaNnfJOwG7c8crJULLbcthFDIiDTkm/w7YnQa2', 'ACTIVE', 2); -- role_id là số
INSERT INTO recruiters (recruiter_id, name, description)
VALUES (2, 'Recruiter Two', 'Mô tả cho Recruiter Two');
