ALTER TABLE skills MODIFY (skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO skills (skill_id, name, industry_id) VALUES (1, 'Java',1);
INSERT INTO skills (skill_id, name, industry_id) VALUES (2, 'Spring Boot',1);
INSERT INTO skills (skill_id, name, industry_id) VALUES (3, 'SQL',1);
INSERT INTO skills (skill_id, name, industry_id) VALUES (4, 'Git',1);
INSERT INTO skills (skill_id, name, industry_id) VALUES (5, 'Docker',1);

ALTER TABLE skills MODIFY (skill_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));
