ALTER TABLE skills MODIFY (skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY );

INSERT INTO skills (skill_id, name) VALUES (1, 'Java');
INSERT INTO skills (skill_id, name) VALUES (2, 'Spring Boot');
INSERT INTO skills (skill_id, name) VALUES (3, 'SQL');
INSERT INTO skills (skill_id, name) VALUES (4, 'Git');
INSERT INTO skills (skill_id, name) VALUES (5, 'Docker');

ALTER TABLE skills MODIFY (skill_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));
