-- Xóa các sequence cũ và tạo lại để đặt lại giá trị
-- DROP SEQUENCE SKILLS_SEQ; -- Không cần drop/create sequence thủ công cho GenerationType.IDENTITY

-- CREATE SEQUENCE SKILLS_SEQ START WITH 1 INCREMENT BY 1; -- Không cần drop/create sequence thủ công cho GenerationType.IDENTITY

-- Loại bỏ dòng ALTER TABLE ... MODIFY (skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY );
-- vì Hibernate sẽ tự động quản lý cột IDENTITY.

INSERT INTO skills (skill_id, name) VALUES (1, 'Java');
INSERT INTO skills (skill_id, name) VALUES (2, 'Spring Boot');
INSERT INTO skills (skill_id, name) VALUES (3, 'SQL');
INSERT INTO skills (skill_id, name) VALUES (4, 'Git');
INSERT INTO skills (skill_id, name) VALUES (5, 'Docker');

-- Dòng này không hợp lệ và đã được loại bỏ:
-- ALTER TABLE skills MODIFY (skill_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7));
