ALTER TABLE stages MODIFY (stage_id NUMBER GENERATED BY DEFAULT AS IDENTITY );


INSERT INTO stages (stage_id, name, stage_order)
VALUES (1, 'CV Screening', 1);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (2, 'Technical Interview', 2);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (3, 'HR Interview', 3);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (4, 'Offer', 4);

----------------------------------------------------------------

INSERT INTO stages (stage_id, name, stage_order)
VALUES (5,'CV Screening', 1);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (6,'Portfolio Review', 2);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (7,'Interview with Designer Lead', 3);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (8,'Final Interview', 4);

INSERT INTO stages (stage_id, name, stage_order)
VALUES (9, 'Offer', 5);


ALTER TABLE stages MODIFY (stage_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 10));