-- Xóa các sequence cũ và tạo lại để đặt lại giá trị
DROP SEQUENCE STAGES_SEQ;

-- Tạo sequence mới với giá trị bắt đầu mong muốn
CREATE SEQUENCE STAGES_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE stages MODIFY (stage_id NUMBER GENERATED BY DEFAULT AS IDENTITY );


-- Stages cho Dev Backend
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (1, 'Sàng lọc CV', 1, 1);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (2, 'Phỏng vấn kỹ thuật vòng 1', 2, 1);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (3, 'Phỏng vấn kỹ thuật vòng 2', 3, 1);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (4, 'Phỏng vấn văn hóa', 4, 1);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (5, 'Gửi offer', 5, 1);

-- Stages cho Dev Frontend
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (6, 'Sàng lọc CV', 1, 2);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (7, 'Làm bài test giao diện', 2, 2);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (8, 'Phỏng vấn kỹ thuật', 3, 2);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (9, 'Gửi offer', 4, 2);

-- Stages cho QA
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (10, 'Sàng lọc CV', 1, 3);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (11, 'Phỏng vấn kỹ thuật', 2, 3);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (12, 'Kiểm tra logic & chi tiết', 3, 3);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (13, 'Phỏng vấn văn hóa', 4, 3);
INSERT INTO stages (stage_id, name, stage_order, recruitment_process_id) VALUES (14, 'Gửi offer', 5, 3);

-- Dòng này không hợp lệ và đã được loại bỏ:
-- ALTER TABLE stages MODIFY (stage_id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 10));
